EVALUATE_PROMPT = """
You will be shown multiple answers generated by a large language model with different token limits.

Your task is to rank these answers from best to worst based on the following criteria:

1.  Correctness: Is the answer factually correct and on-topic?
2.  Reasoning Quality: Does the answer show clear logical steps and thoughtful reasoning?
3.  Completeness: Does it fully address the question with sufficient depth?
4.  Clarity: Is the answer well-organized and easy to understand?

Here are the answers:

{answer_block}

Please return only a Python list of answer indices from best to worst.
For example: `[2, 0, 1]`

Do not explain your ranking.
"""