# 数据集配置
datasets:
  bbh: BBH/navigate.json
  math: AGIEval-MATH/math.json
  gpqa: GPQA-Diamond/diamond.json
  wsc: WSC/wsc.json
  str: StrategyQA/dev.json
  boolq: BoolQ/dev.json

# 模型配置
models:
  - name: "ds7b"
    api-type: "openai"
    base_url: "http://localhost:11434/v1"
    api_key: "ollama"
    params:
      model: "deepseek-r1:7b"
      temperature: 0.7
      max_tokens: 12000
  - name: "o3"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-mtrIkccxaoPMkQkwCKPlsNzvtwDY5eX2m93iUBrFMwd4cwxm"
    params:
      model: "o3-mini"
      temperature: 0
      max_tokens: 12000
  - name: "ds"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-Qi7W3yX9lkwDaV5DHXAxXUVo3rinQCXa2rotl1mtSnBYRITD"
    params:
      model: "deepseek-r1"
      temperature: 0
      max_tokens: 12000
  - name: "ds2"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-mtrIkccxaoPMkQkwCKPlsNzvtwDY5eX2m93iUBrFMwd4cwxm"
    params:
      model: "deepseek-r1"
      temperature: 0
      max_tokens: 12000
  - name: "ds3"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-cWR6XubpwBleOn2TEjhmyIusfcaNZDQoPKrDxILk1TD5rNUs"
    params:
      model: "deepseek-r1"
      temperature: 0
      max_tokens: 12000
  - name: "o4"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-Qi7W3yX9lkwDaV5DHXAxXUVo3rinQCXa2rotl1mtSnBYRITD"
    params:
      model: "o4-mini"
      temperature: 0
      max_tokens: 12000
  - name: "gpt"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-mtrIkccxaoPMkQkwCKPlsNzvtwDY5eX2m93iUBrFMwd4cwxm"
    # api_key: "sk-iX0M9keAJemCgNFqvQMVLyWkcembRT27ix50aymLnvZ18QuT"
    params:
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 4096
  - name: "qwq"
    api-type: "qwq"
    base_url: null   # 不需要 API 地址
    api_key: null    # 不需要 API Key
    params:
      model: "qwq32b"                 # 用于显示/记录，可忽略
      temperature: 0.7
      max_tokens: 16384
      model_path: "/root/qwq32b"     # ✅ QWQ模型路径
      device: "cuda:2"
