# 实验参数
experiment:
  n_i_values: [100, 200, 500, 1000, 2000, 4000]
  max_questions: 50

# 数据集配置
datasets:
  Navigate: navigate.yaml

  navigate: BBH-Navigate/navigate.json
  math: AGIEval-MATH/math.json
  gpqa: GPQA-Diamond/diamond.json
#  FEVER: fever_subset.json
#  LogiQA: logiqa_subset.json

# 模型配置
models:
  - name: "gpt"
    api-type: "openai"
    base_url: "https://api.chatanywhere.tech"
    api_key: "sk-"
    params:
      model: "gpt-3.5-turbo"
      temperature: 0.7
      max_tokens: 4096
  - name: "deepseek"
    api-type: "openai"
    base_url: "http://localhost:11434/v1"
    api_key: "ollama"
    params:
      model: "deepseek-r1:7b"
      temperature: 0.7
      max_tokens: 4096
  - name: "llama"
    api-type: "openai"
    base_url: "http://localhost:11434/v1"
    api_key: "ollama"
    params:
      model: "llama3.1:latest"
      temperature: 0.7
      max_tokens: 4096
  - name: "qwq"
    api-type: "qwq"
    base_url: null   # 不需要 API 地址
    api_key: null    # 不需要 API Key
    params:
      model: "qwq32b"                 # 用于显示/记录，可忽略
      temperature: 0.7
      max_tokens: 4096
      model_path: "/root/qwq32b"     # ✅ QWQ模型路径
      device: "cuda:1"
